name: Zip Files

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Ensure style1 folder exists
      run: |
        mkdir style1
      if: steps.ensure-style1-folder.outputs.result == '1'

    - name: Zip style1 folder
      run: |
        cd style1
        Compress-Archive * -DestinationPath ..\style1.zip
      working-directory: ${{ github.workspace }}

    - name: Upload style1 zip
      uses: actions/upload-artifact@v2
      with:
        name: style1
        path: style1.zip

    - name: Ensure server package folder exists
      run: |
        mkdir server_package
      if: steps.ensure-server-package-folder.outputs.result == '1'

    - name: Zip server package folder
      run: |
        cd server_package
        Compress-Archive * -DestinationPath ..\server_package.zip
      working-directory: ${{ github.workspace }}

    - name: Upload server package zip
      uses: actions/upload-artifact@v2
      with:
        name: server_package
        path: server_package.zip
